# Generated by Django 2.2.6 on 2019-11-04 23:31

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(default=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=0, max_length=30)),
                ('apellido', models.CharField(default=0, max_length=30)),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('codigoNoticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Missing', max_length=70)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.CharField(max_length=500)),
                ('Imagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='proveedorRecompensa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('Logo', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='recompensa',
            fields=[
                ('idrecompensa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('expiracion', models.DateField(null=True)),
                ('activo', models.BooleanField(default=False)),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.proveedorRecompensa')),
            ],
        ),
        migrations.CreateModel(
            name='Reciclaje',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('cantidadReciclada', models.FloatField(default=0)),
                ('tipoMaterial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=0)),
                ('distanciaRecorrida', models.FloatField(default=0)),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('objectoReciclado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Reciclaje')),
            ],
        ),
    ]
