# Generated by Django 2.2.6 on 2019-11-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(default=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=0, max_length=30)),
                ('apellido', models.CharField(default=0, max_length=30)),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('progreso', models.FloatField(default=0)),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Perfil')),
            ],
        ),
    ]
