# Generated by Django 2.2.6 on 2019-11-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
