# Generated by Django 2.2.6 on 2019-11-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='staff',
        ),
    ]
