# Generated by Django 2.2.3 on 2019-10-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20191026_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reciclaje',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('cantidadReciclada', models.FloatField(default=0)),
                ('tipoMaterial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Material')),
            ],
        ),
        migrations.RenameField(
            model_name='estadistica',
            old_name='progreso',
            new_name='distanciaRecorrida',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='id',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='idUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Perfil'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idPerfil',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='estadistica',
            name='objectoReciclado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.Reciclaje'),
        ),
    ]
