# Generated by Django 2.2.3 on 2019-10-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20191028_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='idPerfil',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
