# Generated by Django 2.2.6 on 2019-11-05 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20191105_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.AlterModelManagers(
            name='perfil',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
