# Generated by Django 2.2.6 on 2019-11-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191105_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
