# Generated by Django 2.2.6 on 2019-11-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20191105_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
