# Generated by Django 2.2.6 on 2019-11-02 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('codigoNoticia', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Missing', max_length=70)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.CharField(max_length=500)),
                ('Imagen', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='proveedorRecompensa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('Logo', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='recompensa',
            fields=[
                ('idrecompensa', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('expiracion', models.DateField(null=True)),
                ('activo', models.BooleanField(default=False)),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.proveedorRecompensa')),
            ],
        ),
    ]
