# Generated by Django 2.2.6 on 2019-10-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedorRecompensa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField()),
                ('nombre', models.CharField(max_length=20)),
                ('Logo', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='recompensa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=17)),
                ('expiracion', models.DateField()),
            ],
        ),
    ]
