# Generated by Django 2.2.6 on 2019-10-24 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('codigoNoticia', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Missing', max_length=40)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('descripcion', models.CharField(max_length=70)),
                ('Imagen', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='proveedorRecompensa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('Logo', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='recompensa',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=17)),
                ('expiracion', models.DateField(null=True)),
                ('activo', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.proveedorRecompensa')),
            ],
        ),
    ]
