# Generated by Django 2.2.6 on 2019-10-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recompensa',
            old_name='id',
            new_name='idrecompensa',
        ),
    ]
