# Generated by Django 2.2.6 on 2019-11-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorrecompensa',
            name='Logo',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='idrecompensa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
