# Generated by Django 2.2.6 on 2019-10-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('codigoNoticia', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('Imagen', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
    ]
