# Generated by Django 2.2.6 on 2019-11-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='codigoNoticia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
