# Generated by Django 2.2.6 on 2019-10-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20191024_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recompensa',
            old_name='proveedor',
            new_name='idproveedor',
        ),
    ]
